# Sentimental Analysis using Pytorch

## Understanding of bidirectional RNN works with Pytorch
[Source - Towarddatascience](https://towardsdatascience.com/understanding-bidirectional-rnn-in-pytorch-5bd25a5dd66)
![Bidirectional_RNN](.\Images\Bi_RNN.png)

In [1]:
import numpy as np
import torch, torch.nn as nn
from torch.autograd import Variable

In [2]:
random_input = Variable(torch.FloatTensor(5, 1, 1).normal_(), requires_grad=False)
random_input[:, 0, 0]

tensor([-1.0549,  1.3522,  0.5998, -0.6036, -0.7838])

In [3]:
bi_grus = torch.nn.GRU(input_size=1, hidden_size=1, num_layers=1, batch_first=False, bidirectional=True)

In [4]:
reverse_gru = torch.nn.GRU(input_size=1, hidden_size=1, num_layers=1, batch_first=False, bidirectional=False)

In [7]:
reverse_gru.weight_ih_l0 = bi_grus.weight_ih_l0_reverse
reverse_gru.weight_hh_l0 = bi_grus.weight_hh_l0_reverse
reverse_gru.bias_ih_l0 = bi_grus.bias_ih_l0_reverse
reverse_gru.bias_hh_l0 = bi_grus.bias_hh_l0_reverse

In [8]:
bi_output, bi_hidden = bi_grus(random_input)

In [9]:
reverse_output, reverse_hidden = reverse_gru(random_input[np.arange(4, -1, -1), :, :])

In [11]:
reverse_output[:, 0, 0]

tensor([-0.5546, -0.7654, -0.7683, -0.7503, -0.8539], grad_fn=<SelectBackward>)

In [12]:
bi_output[:, 0, 1]

tensor([-0.8539, -0.7503, -0.7683, -0.7654, -0.5546], grad_fn=<SelectBackward>)

In [13]:
reverse_hidden

tensor([[[-0.8539]]], grad_fn=<ViewBackward>)

In [14]:
bi_hidden[1]

tensor([[-0.8539]], grad_fn=<SelectBackward>)